name: cron workflow
on:
  schedule:
    - cron: "0/5 * * * *"  # تشغيل كل 5 دقائق

jobs:
  cron_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "from workflow"
