name: firstworkflow
on:
  push:
    branches:
      - "main"
jobs:
  first-workflow-job:
    name: first-job
    runs-on: ubuntu-latest
    steps:
      - name: before checkout actions
        run: ls
        shell: bash

      - name: checkout
        uses: actions/checkout@v4  # استخدم v4 لأنها الأحدث

      - name: after checkout actions
        run: ls
        shell: bash
